- id: check-devcontainer
  name: Check devcontainer
  description: Check devcontainer is present for the project
  entry: hooks/check_devcontainer.sh
  language: script
- id: check-dockerfile
  name: Check Dockerfile
  description: Enforce use of Chainguard images in Base images in Dockerfile
  entry: hooks/check_dockerfile.sh
  language: script
- id: check-gitsign
  name: Check gitsign
  description: Check last commit is signed with Sigstore gitsign
  entry: hooks/check_gitsign.sh
  language: script