repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
    name: Check Yaml syntax
    stages: [commit]
- repo: https://github.com/intelops/gitrepos-templates-policies
  rev: v0.0.1
  hooks:
  - id: check-devcontainer
    name: Check devcontainer
    language: system

# Check for Dockerfile in a project
- repo: https://github.com/intelops/gitrepos-templates-policies
  rev: v0.0.1
  hooks:
  - id: check-dockerfile
    name: Check Dockerfile
    language: system

# Check commit signed by gitsign
- repo: https://github.com/intelops/gitrepos-templates-policies
  rev: v0.0.1
  hooks:
  - id: check-gitsign
    name: Check GitSign
    language: system