  - id: check-devcontainer
    name: Check devcontainer
    description: Check devcontainer is present for the project
    entry: check_devcontainer.sh
    language: script
  - id: check-dockerfile
    name: Check Dockerfile
    description: Enforce use of Chainguard images in Base images in Dockerfile
    entry: check_dockerfile.sh
    language: script
  - id: check-gitsign
    name: Check gitsign
    description: Check last commit is signed with Sigstore gitsign
    entry: check_gitsign.sh
    language: script